### ISSUE TITLE
Sire 2016.3 malloc.c error

### ISSUE THREAD

**Issue by Steboss** [michellab/Sire#146]
hi again,

Another error I found in sire-devel is problem with malloc. Once I gave th einput file to somd-freenrg I have immediately this error
```
Starting /home/steboss/sire.app/bin/somd-freenrg: number of threads equals 32
somd-freenrg: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
```
Furthermore, this error appears also when I am trying to run a python script with sire.app/bin/python
What could it be?

Here attached a zip to reproduce the error
[malloc_error.zip](https://github.com/michellab/Sire/files/857791/malloc_error.zip)

**Comment by jmichel80** [comment]
I haven't observed that, do you get this error if using a build from feature_standardstategen ? 
This could be a problem introduced by the switch to a newer GCC in devel.

**Comment by ppxasjsm** [comment]
@chryswoods  included some new vectorisation detection for GCC, fc91c9e, maybe this has something to do with it?

**Comment by Steboss** [comment]
At the moment I have this problem also with feature_standardstategen
I am using gcc 4.8.4, this could be the problem
I will try to update gcc and see if there are any problems

**Comment by ppxasjsm** [comment]
But you have not had this problem before with that branch?

**Comment by chryswoods** [comment]
I've run the test on my mac and don't see a crash on current devel compiled using clang or icpc. I will find time to run it on the linux box to check with gcc. The vectorisation code won't affect malloc. Newer GCC's are pickier with memory allocation, and a lot of my work on the reference counting code was to fix a lot of nasty malloc bugs that are triggered with newer gccs (5.0, 6.0 etc).

**Comment by Steboss** [comment]
@ppxasjsm   no no, it's the first time, but everytime I was using gcc-4.3

**Comment by chryswoods** [comment]
I'm sorry, I've not been able to reproduce this problem.

**Comment by Steboss** [comment]
Thanks @chryswoods 
I will try to re-install/check what's going on my systems 
Thank you very much  :)

**Comment by chryswoods** [comment]
Could you run using gdb? e.g. gdb /path/to/somd-freenrg, and then from there type "run args_to_somd". When it crashes, you can use "bt" to get a backtrace of where the error occurred. This will help us to debug.

**Comment by Steboss** [comment]
@chryswoods  thanks for the hint

So at the moment the situation is:
- on the cluster I am able to rebuild any  Sire but I must use the trick in #133 , namely I have modified build_sire.py  adding ```openmm=7.0``` for conda. If I use openmm 7.1 (along with cuda 7.5) I got the malloc error above
- On the workstation I still have problems, now Segmentation fault
Here the test I have done
1) installing Sire devel with  
openmm=7.0
g++ version 6.2.0
Ubuntu 14.04
cuda 7.0 ( could be this a problem ? ) 
Running SOMD  (so I am trying with simple MD)  with gdb and bt I have this output:
```
0x00002aaac0b2d767 in SireMol::AtomProperty<SireUnits::Dimension::PhysUnit<1, 0, 0, 0, 0, -1, 0> >::toVector() const () from /home/steboss/sire.app/bin/../lib/libSireIO.so.2016

#0  0x00002aaac0b2d767 in SireMol::AtomProperty<SireUnits::Dimension::PhysUnit<1, 0, 0, 0, 0, -1, 0> >::toVector() const () from /home/steboss/sire.app/bin/../lib/libSireIO.so.2016
#1  0x00002aaac0f5856c in SireMove::AtomicVelocityWorkspace::rebuildFromScratch() () from /home/steboss/sire.app/bin/../lib/libSireMove.so.2016
#2  0x00002aaac0f59ae6 in SireMove::AtomicVelocityWorkspace::AtomicVelocityWorkspace(SireMol::MoleculeGroup const&, SireBase::PropertyMap const&) ()
   from /home/steboss/sire.app/bin/../lib/libSireMove.so.2016
#3  0x00002aaac102ac2e in SireMove::OpenMMMDIntegrator::createWorkspace(SireMol::MoleculeGroup const&, SireBase::PropertyMap const&) const [clone .localalias.707] ()
   from /home/steboss/sire.app/bin/../lib/libSireMove.so.2016
#4  0x00002aaac102cb0b in SireMove::OpenMMMDIntegrator::initialise() () from /home/steboss/sire.app/bin/../lib/libSireMove.so.2016
#5  0x00002aaac1ffd1c2 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (SireMove::OpenMMMDIntegrator::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, SireMove::OpenMMMDIntegrator&> > >::operator()(_object*, _object*) () from /home/steboss/sire.app/lib/python3.5/site-packages/Sire/Move/_Move.so
#6  0x00002aaaaf6ee9d7 in boost::python::objects::function::call(_object*, _object*) const () from /home/steboss/sire.app/bin/../lib/libboost_python.so
#7  0x00002aaaaf6eeb98 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
   from /home/steboss/sire.app/bin/../lib/libboost_python.so
#8  0x00002aaaaf6e365b in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/steboss/sire.app/bin/../lib/libboost_python.so
#9  0x00002aaaaf90e541 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<SireError::invalid_index, void (*)(SireError::invalid_index const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(SireError::invalid_index const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) ()
   from /home/steboss/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so
#10 0x00002aaaaf6e363a in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/steboss/sire.app/bin/../lib/libboost_python.so
#11 0x00002aaaaf90e4ff in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<SireError::exception, void (*)(SireError::exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(SireError::exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /home/steboss/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so
#12 0x00002aaaaf6e342f in boost::python::handle_exception_impl(boost::function0<void>) () from /home/steboss/sire.app/bin/../lib/libboost_python.so
#13 0x00002aaaaf6ec2f9 in function_call () from /home/steboss/sire.app/bin/../lib/libboost_python.so
#14 0x00002aaaab18e236 in PyObject_Call (func=0x1086790, arg=<optimised out>, kw=<optimised out>) at Objects/abstract.c:2165
#15 0x00002aaaab268314 in do_call (nk=<optimised out>, na=1, pp_stack=0x7fffffffcb38, func=0x1086790) at Python/ceval.c:4936
#16 call_function (oparg=<optimised out>, pp_stack=0x7fffffffcb38) at Python/ceval.c:4732
---Type <return> to continue, or q <return> to quit---  
#17 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#18 0x00002aaaab26b166 in fast_function (nk=<optimised out>, na=3, n=<optimised out>, pp_stack=0x7fffffffccb8, func=0x2aaac30b3d90) at Python/ceval.c:4803
#19 call_function (oparg=<optimised out>, pp_stack=0x7fffffffccb8) at Python/ceval.c:4730
#20 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#21 0x00002aaaab26b166 in fast_function (nk=<optimised out>, na=0, n=<optimised out>, pp_stack=0x7fffffffce38, func=0x2aaac30c57b8) at Python/ceval.c:4803
#22 call_function (oparg=<optimised out>, pp_stack=0x7fffffffce38) at Python/ceval.c:4730
#23 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#24 0x00002aaaab26bb49 in _PyEval_EvalCodeWithName (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=1, kws=0x2aaaaf3a61d0, kwcount=0, 
    defs=0x2aaac30bc5a0, defcount=1, kwdefs=0x0, closure=0x2aaabc2bbd68, name=0x2aaab0fa65a8, qualname=0x2aaabbff5d98) at Python/ceval.c:4018
#25 0x00002aaaab26adf5 in fast_function (nk=<optimised out>, na=1, n=<optimised out>, pp_stack=0x7fffffffd058, func=0x2aaac30c5840) at Python/ceval.c:4813
#26 call_function (oparg=<optimised out>, pp_stack=0x7fffffffd058) at Python/ceval.c:4730
#27 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#28 0x00002aaaab26bb49 in _PyEval_EvalCodeWithName (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#29 0x00002aaaab26bcd8 in PyEval_EvalCodeEx (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kws=<optimised out>, kwcount=0, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#30 0x00002aaaab26bd1b in PyEval_EvalCode (co=<optimised out>, globals=<optimised out>, locals=<optimised out>) at Python/ceval.c:777
#31 0x00002aaaab291020 in run_mod (arena=0x66f410, flags=0x7fffffffd3a0, locals=0x2aaaaac0b4c8, globals=0x2aaaaac0b4c8, filename=0x2aaaaf3a4030, mod=0x71ce00) at Python/pythonrun.c:976
#32 PyRun_FileExFlags (fp=0x700040, filename_str=<optimised out>, start=<optimised out>, globals=0x2aaaaac0b4c8, locals=0x2aaaaac0b4c8, closeit=<optimised out>, flags=0x7fffffffd3a0)
    at Python/pythonrun.c:929
#33 0x00002aaaab292623 in PyRun_SimpleFileExFlags (fp=0x700040, filename=<optimised out>, closeit=1, flags=0x7fffffffd3a0) at Python/pythonrun.c:396
#34 0x00002aaaab2ad8c7 in run_file (p_cf=0x7fffffffd3a0, filename=0x635b38 L"/home/steboss/sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/somd.py", fp=0x700040) at Modules/main.c:318
#35 Py_Main (argc=<optimised out>, argv=<optimised out>) at Modules/main.c:769
#36 0x0000000000402ca3 in main ()
```

Furthermore,  after finishing the installation, every now and then on the terminal  "Build is in progress" appears. this come from a function in build_sire.py



2) Installing Sire devel as above but openmm 7.1
Again Segmentation fault for SOMD and gdb bt :

```
0x00002aaac0b30807 in SireMol::AtomProperty<SireUnits::Dimension::PhysUnit<1, 0, 0, 0, 0, -1, 0> >::toVector() const () from /home/steboss/sire7.1/sire.app/bin/../lib/libSireIO.so.2016
#0  0x00002aaac0b30807 in SireMol::AtomProperty<SireUnits::Dimension::PhysUnit<1, 0, 0, 0, 0, -1, 0> >::toVector() const () from /home/steboss/sire7.1/sire.app/bin/../lib/libSireIO.so.2016
#1  0x00002aaac0f5b5bc in SireMove::AtomicVelocityWorkspace::rebuildFromScratch() () from /home/steboss/sire7.1/sire.app/bin/../lib/libSireMove.so.2016
#2  0x00002aaac0f5cb36 in SireMove::AtomicVelocityWorkspace::AtomicVelocityWorkspace(SireMol::MoleculeGroup const&, SireBase::PropertyMap const&) ()
   from /home/steboss/sire7.1/sire.app/bin/../lib/libSireMove.so.2016
#3  0x00002aaac102dc7e in SireMove::OpenMMMDIntegrator::createWorkspace(SireMol::MoleculeGroup const&, SireBase::PropertyMap const&) const [clone .localalias.707] ()
   from /home/steboss/sire7.1/sire.app/bin/../lib/libSireMove.so.2016
#4  0x00002aaac102fb5b in SireMove::OpenMMMDIntegrator::initialise() () from /home/steboss/sire7.1/sire.app/bin/../lib/libSireMove.so.2016
#5  0x00002aaac1d621e2 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (SireMove::OpenMMMDIntegrator::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, SireMove::OpenMMMDIntegrator&> > >::operator()(_object*, _object*) () from /home/steboss/sire7.1/sire.app/lib/python3.5/site-packages/Sire/Move/_Move.so
#6  0x00002aaaaf6ee9d7 in boost::python::objects::function::call(_object*, _object*) const () from /home/steboss/sire7.1/sire.app/bin/../lib/libboost_python.so
#7  0x00002aaaaf6eeb98 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
   from /home/steboss/sire7.1/sire.app/bin/../lib/libboost_python.so
#8  0x00002aaaaf6e365b in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/steboss/sire7.1/sire.app/bin/../lib/libboost_python.so
#9  0x00002aaaaf90e561 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<SireError::invalid_index, void (*)(SireError::invalid_index const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(SireError::invalid_index const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) ()
   from /home/steboss/sire7.1/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so
#10 0x00002aaaaf6e363a in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/steboss/sire7.1/sire.app/bin/../lib/libboost_python.so
#11 0x00002aaaaf90e51f in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<SireError::exception, void (*)(SireError::exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(SireError::exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) ()
   from /home/steboss/sire7.1/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so
#12 0x00002aaaaf6e342f in boost::python::handle_exception_impl(boost::function0<void>) () from /home/steboss/sire7.1/sire.app/bin/../lib/libboost_python.so
#13 0x00002aaaaf6ec2f9 in function_call () from /home/steboss/sire7.1/sire.app/bin/../lib/libboost_python.so
#14 0x00002aaaab18e236 in PyObject_Call (func=0x1087390, arg=<optimised out>, kw=<optimised out>) at Objects/abstract.c:2165
#15 0x00002aaaab268314 in do_call (nk=<optimised out>, na=1, pp_stack=0x7fffffffcb28, func=0x1087390) at Python/ceval.c:4936
#16 call_function (oparg=<optimised out>, pp_stack=0x7fffffffcb28) at Python/ceval.c:4732
#17 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#18 0x00002aaaab26b166 in fast_function (nk=<optimised out>, na=3, n=<optimised out>, pp_stack=0x7fffffffcca8, func=0x2aaac2e24730) at Python/ceval.c:4803
#19 call_function (oparg=<optimised out>, pp_stack=0x7fffffffcca8) at Python/ceval.c:4730
#20 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#21 0x00002aaaab26b166 in fast_function (nk=<optimised out>, na=0, n=<optimised out>, pp_stack=0x7fffffffce28, func=0x2aaac2e2c158) at Python/ceval.c:4803
#22 call_function (oparg=<optimised out>, pp_stack=0x7fffffffce28) at Python/ceval.c:4730
#23 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#24 0x00002aaaab26bb49 in _PyEval_EvalCodeWithName (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=1, kws=0x2aaaaf3883d0, kwcount=0, 
    defs=0x2aaac2e215a0, defcount=1, kwdefs=0x0, closure=0x2aaabc2bdc50, name=0x2aaab0fa75a8, qualname=0x2aaabbff1ea0) at Python/ceval.c:4018
#25 0x00002aaaab26adf5 in fast_function (nk=<optimised out>, na=1, n=<optimised out>, pp_stack=0x7fffffffd048, func=0x2aaac2e2c1e0) at Python/ceval.c:4813
#26 call_function (oparg=<optimised out>, pp_stack=0x7fffffffd048) at Python/ceval.c:4730
#27 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#28 0x00002aaaab26bb49 in _PyEval_EvalCodeWithName (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#29 0x00002aaaab26bcd8 in PyEval_EvalCodeEx (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kws=<optimised out>, kwcount=0, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#30 0x00002aaaab26bd1b in PyEval_EvalCode (co=<optimised out>, globals=<optimised out>, locals=<optimised out>) at Python/ceval.c:777
#31 0x00002aaaab291020 in run_mod (arena=0x6d3d20, flags=0x7fffffffd390, locals=0x2aaaaac0b4c8, globals=0x2aaaaac0b4c8, filename=0x2aaaaf3802b0, mod=0x71d7e0) at Python/pythonrun.c:976
#32 PyRun_FileExFlags (fp=0x6f5fa0, filename_str=<optimised out>, start=<optimised out>, globals=0x2aaaaac0b4c8, locals=0x2aaaaac0b4c8, closeit=<optimised out>, flags=0x7fffffffd390)
    at Python/pythonrun.c:929
#33 0x00002aaaab292623 in PyRun_SimpleFileExFlags (fp=0x6f5fa0, filename=<optimised out>, closeit=1, flags=0x7fffffffd390) at Python/pythonrun.c:396
#34 0x00002aaaab2ad8c7 in run_file (p_cf=0x7fffffffd390, filename=0x635cb8 L"/home/steboss/sire7.1/sire.app/pkgs/sire-2016.3.1/share/Sire/scripts/somd.py", fp=0x6f5fa0) at Modules/main.c:318
#35 Py_Main (argc=<optimised out>, argv=<optimised out>) at Modules/main.c:769
#36 0x0000000000402cc3 in main ()
```

Now, the next step I was thinking of installing Sire with openmm 7.0 and cuda 7.5, as in the cluster, to see if maybe cuda is too old and need an update

**Comment by Steboss** [comment]
And finally I won

I installed Sire devel  with openmm 7.0, reinstalling Nvidia drivers and cuda 7.5  with the additional step of exporting in the bashrc:
```
export OPENMM_LIBRARY_DIR=/home/steboss/sire7.0/sire.app/lib
export OPENMM_INCLUDE_DIR=/home/steboss/sire7.0/sire.app/include
export OPENMM_PLUGIN_DIR=/home/steboss/sire7.0/sire.app/lib/plugins
```
and I was finally able to run a simulation with CUDA on my workstation

**Comment by chryswoods** [comment]
The crash with 

```
SireMol::AtomProperty<SireUnits::Dimension::PhysUnit<1, 0, 0, 0, 0, -1, 0> >
```

is a symptom of the deep memory errors that I've been trying to fix in Sire. They only occur with GCC >= 5.0 (i.e. not clang or icpc), and, I believe, relate to errors in ordering of static initialisation of shared data. One fix is to compile with "-O2" only (i.e. not -O3). This was the default for GCC >= 5 in Sire 2016. I thought I had caught all the errors so put this back to -O3. Obviously the errors aren't all caught...

To revert to -O2 change line 523 of corelib/CMakeLists.txt from

```
set ( SIRE_RELEASE_FLAGS "-O3 -ffast-math" )
```

to 

```
set ( SIRE_RELEASE_FLAGS "-O2 -ffast-math" )
```

On older versions of this file there was a test that set this for new GCCs, i.e.

```
    # GCC >= 5 crashes when using -O3
    if ( GCC_MAJOR_VERSION LESS 5 )
      set ( SIRE_RELEASE_FLAGS "-O3 -ffast-math" )
    else()
      set ( SIRE_RELEASE_FLAGS "-O2 -ffast-math" )
    endif()
```

In the meantime I will continue to root out the subtle memory allocation issues that are triggering these bugs.
