### ISSUE TITLE
Error recreating wrappers

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#163]
Hi, 

I am using 2017.2.0 and am unable to recreate wrappers after following the instructions in

$HOME/software/devel/sire/wrapper/HOWTO_GENERATE_WRAPPERS

This is the error message I get

[ julien@mechagodzilla: wrapper ]$ $HOME/sire.app/bin/python AutoGenerate/scanheaders.py /home/julien/software/devel/sire/corelib/src/libs .
[ julien@mechagodzilla: wrapper ]$ cd MM/
[ julien@mechagodzilla: MM ]$ $HOME/sire.app/bin/python ../AutoGenerate/create_wrappers.py
/home/julien/sire.app/lib/python3.5/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/home/julien/sire.app/lib/python3.5/site-packages/pyplusplus/decl_wrappers/algorithm.py:51: DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6
  __RE_VALID_IDENTIFIER = re.compile( r"[_a-z]\w*", re.I | re.L | re.U )
Using gccxml from /usr/bin/gccxml
Generating wrappers including OpenMM from /home/julien/sire.app/bin/../include
INFO Parsing source file "active_headers.h" ... 
In file included from /home/julien/software/devel/sire/corelib/src/libs/SireBase/property.h:32,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireBase/propertymap.h:36,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMM/amberparams.h:32,
                 from active_headers.h:6:
/home/julien/software/devel/sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:167: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:167: error: invalid constructor; you probably meant 'SireBase::SharedPolyPointer<T> (const SireBase::SharedPolyPointer<T>&)'
/home/julien/software/devel/sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:173: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireBase/sharedpolypointer.hpp:186: error: expected ',' or '...' before '&&' token
In file included from /home/julien/software/devel/sire/corelib/src/libs/SireMM/amberparams.h:33,
                 from active_headers.h:6:
/home/julien/software/devel/sire/corelib/src/libs/SireBase/shareddatapointer.hpp:67: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireBase/shareddatapointer.hpp:67: error: invalid constructor; you probably meant 'SireBase::SharedDataPointer<T> (const SireBase::SharedDataPointer<T>&)'
/home/julien/software/devel/sire/corelib/src/libs/SireBase/shareddatapointer.hpp:73: error: expected ',' or '...' before '&&' token
In file included from /home/julien/software/devel/sire/corelib/src/libs/SireMol/atomproperty.hpp:41,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/atom.h:36,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/selector.hpp:35,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/partialmolecule.h:157,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMM/amberparams.h:39,
                 from active_headers.h:6:
/home/julien/software/devel/sire/corelib/src/libs/SireBase/packedarray2d.hpp:140: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireBase/packedarray2d.hpp:140: error: invalid constructor; you probably meant 'SireBase::detail::SharedArray2DPtr<T> (const SireBase::detail::SharedArray2DPtr<T>&)'
/home/julien/software/devel/sire/corelib/src/libs/SireBase/packedarray2d.hpp:172: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireBase/packedarray2d.hpp: In member function 'SireBase::detail::SharedArray2DPtr<T>& SireBase::detail::SharedArray2DPtr<T>::operator=(SireBase::detail::SharedArray2DPtr<T>)':
/home/julien/software/devel/sire/corelib/src/libs/SireBase/packedarray2d.hpp:174: error: 'other' was not declared in this scope
In file included from /home/julien/software/devel/sire/corelib/src/libs/SireMol/atomcoords.h:34,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/atom.h:37,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/selector.hpp:35,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMol/partialmolecule.h:157,
                 from /home/julien/software/devel/sire/corelib/src/libs/SireMM/amberparams.h:39,
                 from active_headers.h:6:
/home/julien/software/devel/sire/corelib/src/libs/SireVol/coordgroup.h: At global scope:
/home/julien/software/devel/sire/corelib/src/libs/SireVol/coordgroup.h:107: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireVol/coordgroup.h:107: error: invalid constructor; you probably meant 'SireVol::detail::CGSharedPtr<T> (const SireVol::detail::CGSharedPtr<T>&)'
/home/julien/software/devel/sire/corelib/src/libs/SireVol/coordgroup.h:139: error: expected ',' or '...' before '&&' token
/home/julien/software/devel/sire/corelib/src/libs/SireVol/coordgroup.h: In member function 'SireVol::detail::CGSharedPtr<T>& SireVol::detail::CGSharedPtr<T>::operator=(SireVol::detail::CGSharedPtr<T>)':
/home/julien/software/devel/sire/corelib/src/libs/SireVol/coordgroup.h:141: error: 'other' was not declared in this scope
Traceback (most recent call last):
  File "../AutoGenerate/create_wrappers.py", line 664, in <module>
    gccxml_config=xml_generator_config )
  File "/home/julien/sire.app/lib/python3.5/site-packages/pyplusplus/module_builder/boost_python_builder.py", line 95, in __init__
    , indexing_suite_version)
  File "/home/julien/sire.app/lib/python3.5/site-packages/pyplusplus/module_builder/boost_python_builder.py", line 138, in __parse_declarations
    decls = reader.read_files( files, compilation_mode )
  File "/home/julien/sire.app/lib/python3.5/site-packages/pygccxml/parser/project_reader.py", line 249, in read_files
    return self.__parse_file_by_file(files)
  File "/home/julien/sire.app/lib/python3.5/site-packages/pygccxml/parser/project_reader.py", line 278, in __parse_file_by_file
    decls = reader.read_file(header)
  File "/home/julien/sire.app/lib/python3.5/site-packages/pygccxml/parser/source_reader.py", line 380, in read_file
    return self.read_cpp_source_file(source_file)
  File "/home/julien/sire.app/lib/python3.5/site-packages/pygccxml/parser/source_reader.py", line 399, in read_cpp_source_file
    xml_file = self.create_xml_file(ffname)
  File "/home/julien/sire.app/lib/python3.5/site-packages/pygccxml/parser/source_reader.py", line 343, in create_xml_file
    " xml file does not exist")
RuntimeError: Error occurred while running GCCXML xml file does not exist

**Comment by Steboss** [comment]
Could be related to #157 ?

**Comment by Steboss** [comment]
I am sorry, I meant #154

**Comment by jmichel80** [comment]
I don't think so, this isn't an import error.

**Comment by jmichel80** [comment]
@chryswoods I gave it another go with a fresh install of 2017.2 on another system but have hit exactly the same issue.
Could this be due to a change of version of a python dependency?

**Comment by jmichel80** [comment]
quick update, the errors are all due to incorrect C++ syntax for a bunch of hpp files. Typically an extra & like

(...)
    SharedArray2DPtr(SharedArray2DPtr &&other) : ptr(other.ptr)
 (...)

I fixed those manually, but have no idea how they ended up in the source. Were these source files autogenerated ?

**Comment by Steboss** [comment]
I try to install feature_elecreweight , but I had  errors like this one:

```
/home/steboss/Software/sire_electrostatics/corelib/src/libs/SireBase/shareddatapointer.hpp:168:1: error: prototype for 'SireBase::SharedDataPointer<T>::SharedDataPointer(SireBase::SharedDataPointer<T>&&)' does not match any in class 'SireBase::SharedDataPointer<T>'
 SharedDataPointer<T>::SharedDataPointer(SharedDataPointer<T> &&other)
 ^
```

Thus, I modified:   SireBase/shareddatapointer.hpp   , SireBase/sharedpolypoint_cast.hpp and SireBase/sharedpolypointer.hpp  as in  feature_pbcorrection 

Eventually, the installation went fine. 
however, when I am trying to  use the code ```RFcutoff.py```  (commit  https://github.com/michellab/Sire/commit/68db6562583faf7be0b5f1f264f1ef7d02b295c8 ), with the new implemented wrappers, I encounter a random memory error:
``` *** Error in `/home/steboss/sire_electrostatics/sire.app/bin/rf-tailcorrection': double free or corruption (!prev): 0x0000000003a4cef0 ***
 ```
random, since the script  crashes at different points anytime I am running it.
I run the script with gdb and this is the output:
```
#0  0x00002aaaaca0fc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002aaaaca13028 in __GI_abort () at abort.c:89
#2  0x00002aaaaca4c2a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x2aaaacb5e310 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00002aaaaca5882e in malloc_printerr (ptr=<optimised out>, str=0x2aaaacb5e3f8 "double free or corruption (!prev)", action=1) at malloc.c:4998
#4  _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at malloc.c:3842
#5  0x00002aaab81b90a4 in SireMol::AtomProperty<SireMaths::Vector>::set(SireMol::CGAtomIdx const&, SireMaths::Vector const&) ()
   from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libSireMol.so.2017
#6  0x00002aaab2ee377f in boost::python::detail::caller_arity<3u>::impl<SireMol::AtomProperty<SireMaths::Vector>& (SireMol::AtomProperty<SireMaths::Vector>::*)(SireMol::CGAtomIdx const&, SireMaths::Vector const&), boost::python::return_self<boost::python::default_call_policies>, boost::mpl::vector4<SireMol::AtomProperty<SireMaths::Vector>&, SireMol::AtomProperty<SireMaths::Vector>&, SireMol::CGAtomIdx const&, SireMaths::Vector const&> >::operator()(_object*, _object*) () from /home/steboss/sire_electrostatics/sire.app/lib/python3.5/site-packages/Sire/Mol/_Mol.so
#7  0x00002aaaaf72912c in boost::python::objects::function::call(_object*, _object*) const () from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libboost_python.so
#8  0x00002aaaaf729478 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
   from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libboost_python.so
#9  0x00002aaaaf71f0b3 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libboost_python.so
#10 0x00002aaaaf94a6b1 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<SireError::invalid_index, void (*)(SireError::invalid_index const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(SireError::invalid_index const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) ()
   from /home/steboss/sire_electrostatics/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so
#11 0x00002aaaaf71f098 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libboost_python.so
#12 0x00002aaaaf94a66f in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<SireError::exception, void (*)(SireError::exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(SireError::exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boo---Type <return> to continue, or q <return> to quit---
st::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) ()
   from /home/steboss/sire_electrostatics/sire.app/lib/python3.5/site-packages/Sire/Error/_Error.so
#13 0x00002aaaaf71ee7d in boost::python::handle_exception_impl(boost::function0<void>) () from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libboost_python.so
#14 0x00002aaaaf727df9 in function_call () from /home/steboss/sire_electrostatics/sire.app/bin/../lib/libboost_python.so
#15 0x00002aaaab18d236 in PyObject_Call (func=0xa2eee0, arg=<optimised out>, kw=<optimised out>) at Objects/abstract.c:2165
#16 0x00002aaaab267314 in do_call (nk=<optimised out>, na=3, pp_stack=0x7fffffffcb98, func=0xa2eee0) at Python/ceval.c:4936
#17 call_function (oparg=<optimised out>, pp_stack=0x7fffffffcb98) at Python/ceval.c:4732
#18 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#19 0x00002aaaab26a166 in fast_function (nk=<optimised out>, na=4, n=<optimised out>, pp_stack=0x7fffffffcd18, func=0x2aaad0f73c80) at Python/ceval.c:4803
#20 call_function (oparg=<optimised out>, pp_stack=0x7fffffffcd18) at Python/ceval.c:4730
#21 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#22 0x00002aaaab26a166 in fast_function (nk=<optimised out>, na=0, n=<optimised out>, pp_stack=0x7fffffffce98, func=0x2aaad20da158) at Python/ceval.c:4803
#23 call_function (oparg=<optimised out>, pp_stack=0x7fffffffce98) at Python/ceval.c:4730
#24 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#25 0x00002aaaab26ab49 in _PyEval_EvalCodeWithName (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=1, kws=0x2aaaaabd69b0, kwcount=0, 
    defs=0x2aaac1193f78, defcount=1, kwdefs=0x0, closure=0x2aaac1193ef0, name=0x2aaab08eedf8, qualname=0x2aaab0646920) at Python/ceval.c:4018
#26 0x00002aaaab269df5 in fast_function (nk=<optimised out>, na=1, n=<optimised out>, pp_stack=0x7fffffffd0b8, func=0x2aaad20da1e0) at Python/ceval.c:4813
#27 call_function (oparg=<optimised out>, pp_stack=0x7fffffffd0b8) at Python/ceval.c:4730
#28 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>) at Python/ceval.c:3236
#29 0x00002aaaab26ab49 in _PyEval_EvalCodeWithName (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#30 0x00002aaaab26acd8 in PyEval_EvalCodeEx (_co=<optimised out>, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kws=<optimised out>, kwcount=0, 
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#31 0x00002aaaab26ad1b in PyEval_EvalCode (co=<optimised out>, globals=<optimised out>, locals=<optimised out>) at Python/ceval.c:777
#32 0x00002aaaab290020 in run_mod (arena=0x6ef260, flags=0x7fffffffd400, locals=0x2aaaaac0b408, globals=0x2aaaaac0b408, filename=0x2aaaaf3ae620, mod=0x71ea90) at Python/pythonrun.c:976
#33 PyRun_FileExFlags (fp=0x700da0, filename_str=<optimised out>, start=<optimised out>, globals=0x2aaaaac0b408, locals=0x2aaaaac0b408, closeit=<optimised out>, flags=0x7fffffffd400)
    at Python/pythonrun.c:929
#34 0x00002aaaab291623 in PyRun_SimpleFileExFlags (fp=0x700da0, filename=<optimised out>, closeit=1, flags=0x7fffffffd400) at Python/pythonrun.c:396
#35 0x00002aaaab2ac8c7 in run_file (p_cf=0x7fffffffd400, filename=0x6341e8 L"/home/steboss/sire_electrostatics/sire.app/pkgs/sire-2017.2.0/share/Sire/scripts/rf-tailcorrection.py", fp=0x700da0)
    at Modules/main.c:318
#36 Py_Main (argc=<optimised out>, argv=<optimised out>) at Modules/main.c:769
#37 0x0000000000402ca3 in main ()
```

**Comment by chryswoods** [comment]
The issue here is that the extra "&" is not an error, but is part of C++-11. It is the "move" operator, and changing it will lead to memory corruption / crashes as you see above.

The problem is that gccxml cannot parse C++-11, and so fails. The solution is to install CastXML (https://github.com/CastXML/CastXML). This is a drop-in replacement for gccxml which is based on clang, rather than gcc. This is the program used to generate the wrappers on OS X. (as you can see on the gccxml page, they now redirect you to castxml - https://gccxml.github.io/HTML/Index.html).

If castxml is in the PATH before gccxml, then pygccxml will automatically pick it up and use it. I am sorry, as I should have updated the documentation to make this change in tool clear, and to add in instructions to install castxml. I'd hope that you can now apt-get it. I found compiling it to be straightforward.

**Comment by Steboss** [comment]
Great, thanks for the explanation @chryswoods 
@jmichel80  I will re-setup the  ```feature_elecreweight``` branch  accordingly

**Comment by jmichel80** [comment]
@steboss 

I still get coredump after a fresh build from the code checked out on feature_elecreweight, e.g.

[ julien@mechagodzilla: lambda-0.000 ]$ ~/sire.app/bin/rf-tailcorrection -t ../input/SYSTEM.top -c ../input/SYSTEM.crd -m ../input/MORPH.pert -l 0.0 -r traj000000001.dcd -s 1000 
Starting /home/julien/sire.app/bin/rf-tailcorrection: number of threads equals 16


Running a rf-tailcorrection calculation using files ../input/SYSTEM.top, ../input/SYSTEM.crd, ../input/MORPH.pert and traj000000001.dcd.
Namespace(author=False, config=None, coordinate_file='../input/SYSTEM.crd', disable_crf=False, help_config=False, lambda_val='0.0', morph_file='../input/MORPH.pert', step='1000', topology_file='../input/SYSTEM.top', traj_file='traj000000001.dcd', use_solute_inter_nrg=False, version=False)
Using parameters:
===============
crdfile == ../input/SYSTEM.crd
lambda_val == 0.0
morphfile == ../input/MORPH.pert
step_frame == 1000
topfile == ../input/SYSTEM.top
trajfile == traj000000001.dcd
===============
### Running RF tail correction calculation on unknown ###
lambda is 0.0
Create the System...
Selecting dummy groups
Creating force fields... 
Creating force fields... 
Processing frame 1 
CURRENT POSITION 1 
READ TRAJECTORY
Processing system shortc
Here we are processing traj
Here we know the molnums
Cycling through the molecules
cycling through atoms
setting new coordinates
cycling through atoms
setting new coordinates
setting new coordinates
*** Error in `/home/julien/sire.app/bin/rf-tailcorrection': double free or corruption (!prev): 0x00000000044f6420 ***
Aborted (core dumped)

**Comment by Steboss** [comment]
I am going to investigate
Very strange, on my workstation works perfectly

**Comment by chryswoods** [comment]
Run the program a few times. Any crash that involves reading or writing memory from AtomProperty<T> is related to the GCC >=5 behaviour (i.e. only manifested when compiled with GCC >= 5, and would crash randomly, about 1 time out of 10 runs). I believe I fixed this by completely rewriting the underlying memory handling of AtomProperty<T> etc., hence the addition of the "&&" move constructors etc.

When I use GitHub to compare devel against feature_elecreweight I see a lot of small changes in packedarray2d.hpp, shareddatapointer.hpp, sharedpolypointer.hpp etc. (https://github.com/michellab/Sire/compare/feature_elecreweight). Please could you revert these changes back so that they match devel.

Also, as a side note, I see that the python wrappers you generate have lost all of the source-code documentation that is exported to python. For example, you can see in the wrappers for wrapper/MM/AmberAngle.pypp.cpp that the second argument to the exposer is an empty string in your branch, but is the correct documentation string in devel. I will raise this an a new issue as it suggests there is a bug in the code that extracts this documentation on your machine.

**Comment by chryswoods** [comment]
Closing due to inactivity and it appears that the issue is fixed.
