### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#379]
I upgradted to the latest devel code today. I compiled the code from scratch without errors on a Ubuntu 18.04 LTS workstation. However executing ./compile_sire.sh a second time now causes a build error

```
[ julien@mechagodzilla: Sire ]$ ./compile_sire.sh 
Where would you like to install Sire? [/home/julien/sire.app]: 
Installing into directory '/home/julien/sire.app'
** Running the conda activate script... **
** . "/home/julien/sire.app/bin/activate"
** Running the Python install script... **
** /home/julien/sire.app/bin/python build/build_sire.py  **
Compiling on Linux
Number of cores used for compilation = 16
Continuing the Sire install using /home/julien/sire.app/bin/python build/build_sire.py
pip is already installed...
ipython is already installed...
pytest is already installed...
nose is already installed...
netCDF4 is already installed...
boost is already installed...
gsl is already installed...
TBB is already installed...
Qt5 is already installed...
Traceback (most recent call last):
  File "build/build_sire.py", line 210, in <module>
    import pymbar
  File "/home/julien/sire.app/lib/python3.8/site-packages/pymbar/__init__.py", line 31, in <module>
    from pymbar import timeseries, testsystems, confidenceintervals, version
  File "/home/julien/sire.app/lib/python3.8/site-packages/pymbar/timeseries.py", line 62, in <module>
    from pymbar.utils import ParameterError
  File "/home/julien/sire.app/lib/python3.8/site-packages/pymbar/utils.py", line 31, in <module>
    import numexpr
  File "/home/julien/sire.app/lib/python3.8/site-packages/numexpr/__init__.py", line 33, in <module>
    from numexpr.expressions import E
  File "/home/julien/sire.app/lib/python3.8/site-packages/numexpr/expressions.py", line 20, in <module>
    from setuptools._vendor.packaging.version import parse, Version
  File "/home/julien/sire.app/lib/python3.8/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/julien/sire.app/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/julien/sire.app/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 72, in do_override
    ensure_local_distutils()
  File "/home/julien/sire.app/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /home/julien/sire.app/lib/python3.8/distutils/core.py

```

**Comment by chryswoods** [comment]
That looks like something weird has gone on in distutils or pymbar? We haven't changed anything in the compilation of Sire, and I can't think of a mechanism by which Sire could mess up conda / Python like that?

Could you delete and then reinstall from scratch? If the problem persists then we will try and debug. If not, then we can put this down to "conda weirdness".

**Comment by lohedges** [comment]
Looks like it could be related to [this](https://github.com/pypa/setuptools/issues/3089).
