### ISSUE TITLE
WaterSwap throws SireError

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#421]
WaterSwap seems to be broken in the current development version of Flare and it also throws a `SireError` when running it from Sire release version 2023.0.0

The command I used is: `waterswap -c ../input/SYSTEM.rst7 -t ../input/SYSTEM.prm7 -l 9G6`

The input files and the ones that were generated before the error can be found at:  ` https://github.com/SofiaBariami/sharing_files/tree/master/waterswap_files ` 

WaterSwap runs until this point:
```
Creating WSRC system constraints...

Using lambda values: [0.005, 0.071, 0.137, 0.203, 0.269, 0.335, 0.401, 0.467, 0.533, 0.599, 0.665, 0.731, 0.797, 0.863, 0.929, 0.995]
Adding the identity constraint...
Choosing swap waters from both the protein box and water box.
The number of candidates for the swap water equals: 605

Adding system monitors...
```
And then it throws the following error: 

```
Energies of this system at lambda == 0...
Traceback (most recent call last):
  File "/home/sofia/miniconda3/share/Sire/scripts/waterswap.py", line 205, in <module>
    WSRC.run(params)
  File "/home/sofia/miniconda3/lib/python3.9/site-packages/sire/legacy/Tools/__init__.py", line 175, in inner
    retval = func()
  File "/home/sofia/miniconda3/lib/python3.9/site-packages/sire/legacy/Tools/WSRC.py", line 2908, in run
    (wsrc_system, wsrc_moves) = loadWSRC()
  File "/home/sofia/miniconda3/lib/python3.9/site-packages/sire/legacy/Tools/WSRC.py", line 2748, in loadWSRC
    wsrc_system = mergeSystems(proteinsys, watersys, ligand_mol)
  File "/home/sofia/miniconda3/lib/python3.9/site-packages/sire/legacy/Tools/WSRC.py", line 2625, in mergeSystems
    printEnergies(system.energies(), sys.stdout)
UserWarning: SireError::incomplete_code: NEED TO WRITE THE CODE FOR NON_STRICT SELECTION OF 1-4 PAIRS (call sire.error.get_last_error_details() for more info)
```

**Comment by chryswoods** [comment]
Thanks for letting me know - I am trying to reproduce this on my computer. There's been quite a few changes in Sire for 2023.0.0 to modernise the API. We're trying not to break anything. 2023.0.0 is a "development" pre-release, which we had to put out to enable BioSimSpace to be ported. WaterSwap should be fully working again by 2023.1.0 (due later this month)

**Comment by chryswoods** [comment]
I've looked through and confirm that this was a problem with `2023.0.0`. It was introduced as part of general bug fixing, which accidentally triggered the code path that led to the "INCOMPLETE CODE" message and error.

Fortunately, this was fixed in [this commit](https://github.com/michellab/Sire/commit/04e4d38b7dda72f26858d547f2a595c4e4f21534) in September (2023.0.0 was released in July). Versions `2023.0.1` or later should work. I have tested it using the pre-release for `2023.1.0` (installable via `mamba install -c "openbiosim/label/dev" sire`) and your system loads and runs correctly with water swap.

I've confirmed that `waterswap` runs correctly and generates the free energies I expect for my original test system, and that it also now runs properly for your system. 

We are likely to release 2023.1.0 very soon (end of this week or beginning of next week). You can use this now via the mamba install link I've given above. We should talk to Cresset and encourage them to move to 2023.1.0 before they release Flare.
