### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by leelasd** [michellab/Sire#57]
Hi I tried using the installation instructions (given for Ubuntu) to install SIRE on mac. Everything worked fine, up to point 8. When I tried installing the setuptools module from sire-python it gave me an error.

```
$cd /Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools
$~/sire.app/bundled/bin/python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    exec(init_file.read(), command_ns)
  File "<string>", line 8, in <module>
  File "/Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools/setuptools/dist.py", line 7, in <module>
    from setuptools.command.install import install
  File "/Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/Users/Sriram/Software/Sire-master/build_wrapper/build_bundled/setuptools/pkg_resources.py", line 16, in <module>
    import sys, os, time, re, imp, types, zipfile, zipimport
ImportError: No module named 'time'
```
Can you please tell where I am getting it wrong??

**Comment by ppxasjsm** [comment]
Installation on Mac is still a bit experimental. We are currently working on improving this, in particular the bundling of python will change in the very near future. 
From what I can see, what you posted there might be two issues. 
1. Can you check that your python installation is working fine:
~/sire.app/bin/python
Then try if you can import time:
import time
2. you need actually give the install prefix, i.e.:
~/sire.app/bin/python setup.py install --prefix=~/sire.app/bundled/
Those are the two obvious things I can see at the moment.

**Comment by chryswoods** [comment]
This is a problem with the Yosemite. The version of Python bundled with Sire (3.3) doesn't work with Yosemite, and the standard python modules are not built correctly (e.g. time). You will either need to use the binary Sire distribution from siremol.org (2014.4), or, if you are wanting the features such as nautilus, openmm etc., then you will need to wait for us to implement a fix.

**Comment by leelasd** [comment]
Thank you very much. It seems like my installation of Sire is not working. But I followed this instructions on a Fedora system and installed SIRE core library.
