### ISSUE TITLE
writing out gradients with more than 100 cycles

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#68]
Looks like there is an error in openmmmd.py that cannot handle more than 100 cycles based on a given set of input parameters. 

The error output after reaching 101 cycles:
```
Starting /home/common/dev_sire.app/bin/somd-freenrg: number of threads equals 32
Traceback (most recent call last):
  File "/home/common/dev_sire.app/share/Sire/scripts/somd-freenrg.py", line 142, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/common/dev_sire.app/bundled/lib/python3.3/site-packages/Sire/Tools/__init__.py", line 135, in inner
    retval = func()
  File "/home/common/dev_sire.app/bundled/lib/python3.3/site-packages/Sire/Tools/OpenMMMD.py", line 1554, in runFreeNrg
    grads[lambda_val.val].accumulate(gradients[i-1])
IndexError: list index out of range
srun: error: node011: task 0: Exited with exit code 1
```
The config input file used was:
```
topfile = ../../input/SYSTEM.top
crdfile = ../../input/SYSTEM.crd
morphfile = ../../input/MORPH.pert
nmoves = 10000
ncycles = 150
buffered coordinates frequency = 500
save coordinates = True
timestep = 4 * femtosecond
constraint = allbonds
hydrogen mass repartitioning factor = 4.0
cutoff type = cutoffperiodic
cutoff distance = 10*angstrom
barostat = True
andersen = True
energy frequency = 100
precision = mixed
minimise = True
equilibrate = True
equilibration iterations = 500
center solute = True
coulomb power = 1
shift delta = 2
minimal coordinate saving = True
lambda array = 0.00, 0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375, 1 
```

**Comment by ppxasjsm** [comment]
Yep. I have that on my to do list already...
